### ISSUE TITLE
ObservedObject

### ISSUE THREAD

**Issue by fahd9567** [fahd9567/ar#1]
i have an issue in this code call ( Reference to generic type 'ObservedObject' requires arguments in <...> )

`import SwiftUI

class SessionSettings: ObservedObject {
    @Published var isPeopleOcclusionEnabled: Bool = false
    @Published var isObjectOcclusionEnabled: Bool = false
    @Published var isLidarDebugEnabled: Bool = false
    @Published var isMultiuserEnabled: Bool = false
}`

**Comment by AndreasInk** [comment]
It's supposed to be ObservableObject not ObservedObject, this should be super helpful...
https://www.hackingwithswift.com/quick-start/swiftui/how-to-use-observedobject-to-manage-state-from-external-objects
