### ISSUE TITLE
StateObject

### ISSUE THREAD

**Issue by fahd9567** [fahd9567/ar#2]
i have an another issue call ( Generic struct 'StateObject' requires that 'SessionSettings' conform to 'ObservableObject' )

`import SwiftUI

@main
struct testApp: App {
    @StateObject var placementSettings = PlacementSettings()
    @StateObject var sessionSettings = SessionSettings()
    
    var body: some Scene {
        WindowGroup {
            ContentView()
                .environmentObject(placementSettings)
                .environmentObject(sessionSettings)
        }
    }
}`

**Comment by AndreasInk** [comment]
Try adding ObservableObject to SessionSettings so it'll look something like this..
class SessionSettings: ObservableObject {
