### ISSUE TITLE
struct RecentGrid: View

### ISSUE THREAD

**Issue by fahd9567** [fahd9567/ar#4]
in this page i have an issue call ( Cannot find 'name' in scope )

`struct RecentGrid: View {
    @EnvironmentObject var placementSettings: PlacementSettings
    @Binding var showBrowse: Bool
    
    var body: some View {
        if !self.placementSettings.recentlyPlaced.isEmpty {
            HorizontalGrid(showBrowse: $showBrowse, title: "Recents", items: getRecentsUniqueOrdered())
        }
    }
    
    func getRecentsUniqueOrdered() -> [Model] {
        var recentsUniqueOrderArray: [Model] = []
        var modelNameSet: Set<String> = []
        
        for model in self.placementSettings.recentlyPlaced.reversed() {
            
            if !modelNameSet.contains(model,name) {
                recentsUniqueOrderArray.append(model)
                modelNameSet.insert(model.name)
            }
        }
        
        return recentsUniqueOrderArray
    }
}`

**Comment by AndreasInk** [comment]
You said model,name it should be model.name
